"""
Facial Blendshapes Generation via Deformation Transfer (ARKit 52 Blendshapes)

Transfers 52 standard Apple ARKit facial blendshapes from template meshes onto arbitrary
target 3D character/head meshes generated by TRELLIS.2, Hunyuan3D, or uploaded by user.
Produces glTF 2.0 morph targets compatible with Three.js, Unreal Engine, Unity, Blender,
and Apple ARKit / FaceID tracking.

Reference:
- vasiliskatr/deformation_transfer_ARkit_blendshapes (MIT License)
- Sumner & Popović: Deformation Transfer for Triangle Meshes (SIGGRAPH 2004)
"""

import os
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any

import numpy as np
import trimesh
from scipy.spatial import cKDTree


# Standard Apple ARKit eye and eyebrow blendshapes (Focused purely on eye expressions)
ARKIT_BLENDSHAPES = [
    # Eye Blinks (Nháy mắt / Nhắm mắt)
    "eyeBlinkLeft", "eyeBlinkRight",
    # Eye Squints (Nheo mắt / Híp mắt)
    "eyeSquintLeft", "eyeSquintRight",
    # Eye Wide (Mở to mắt / Trố mắt)
    "eyeWideLeft", "eyeWideRight",
    # Eye Gaze / Look Directions (Hướng nhìn / Đảo mắt)
    "eyeLookUpLeft", "eyeLookUpRight",
    "eyeLookDownLeft", "eyeLookDownRight",
    "eyeLookInLeft", "eyeLookInRight",
    "eyeLookOutLeft", "eyeLookOutRight",
    # Eyebrows (Nhíu mày / Nhướn mày)
    "browDownLeft", "browDownRight",
    "browInnerUp", "browOuterUpLeft", "browOuterUpRight"
]

EXPRESSION_PRESETS = {
    "wink_right": {
        "name": "Nháy mắt phải (Wink Right)",
        "icon": "😉",
        "weights": {
            "eyeBlinkRight": 1.0,
            "eyeSquintRight": 0.3
        }
    },
    "wink_left": {
        "name": "Nháy mắt trái (Wink Left)",
        "icon": "😜",
        "weights": {
            "eyeBlinkLeft": 1.0,
            "eyeSquintLeft": 0.3
        }
    },
    "blink": {
        "name": "Nhắm 2 mắt (Blink Both)",
        "icon": "😌",
        "weights": {
            "eyeBlinkLeft": 1.0,
            "eyeBlinkRight": 1.0
        }
    },
    "squint": {
        "name": "Nheo mắt (Squint Eyes)",
        "icon": "🧐",
        "weights": {
            "eyeSquintLeft": 0.85,
            "eyeSquintRight": 0.85
        }
    },
    "wide": {
        "name": "Mở to mắt (Wide Eyes)",
        "icon": "😳",
        "weights": {
            "eyeWideLeft": 1.0,
            "eyeWideRight": 1.0,
            "browInnerUp": 0.7
        }
    },
    "frown": {
        "name": "Nhíu mắt / Cau có (Frown Eyes)",
        "icon": "😠",
        "weights": {
            "browDownLeft": 1.0,
            "browDownRight": 1.0,
            "eyeSquintLeft": 0.5,
            "eyeSquintRight": 0.5
        }
    },
    "look_up": {
        "name": "Đảo mắt lên (Look Up)",
        "icon": "🙄",
        "weights": {
            "eyeLookUpLeft": 0.9,
            "eyeLookUpRight": 0.9,
            "browInnerUp": 0.4
        }
    },
    "look_left": {
        "name": "Liếc mắt trái (Look Left)",
        "icon": "👈",
        "weights": {
            "eyeLookInRight": 0.85,
            "eyeLookOutLeft": 0.85
        }
    },
    "look_right": {
        "name": "Liếc mắt phải (Look Right)",
        "icon": "👉",
        "weights": {
            "eyeLookInLeft": 0.85,
            "eyeLookOutRight": 0.85
        }
    }
}



class FacialBlendshapesTransfer:
    """
    Deformation Transfer engine that maps 52 ARKit facial blendshapes onto arbitrary target 3D meshes.
    """

    def __init__(self, assets_dir: Optional[str] = None):
        if assets_dir is None:
            assets_dir = str(Path(__file__).resolve().parent / "assets" / "arkit_blendshapes")
        
        self.assets_dir = Path(assets_dir)
        self.source_neutral_path = self.assets_dir / "Neutral.obj"
        
        self.source_neutral: Optional[trimesh.Trimesh] = None
        self.source_deltas: Dict[str, np.ndarray] = {}
        self.R_align: np.ndarray = np.eye(3, dtype=np.float32)
        self.source_landmarks_3d: Optional[Dict[str, np.ndarray]] = None
        self._is_loaded = False
        
    def load_templates(self) -> bool:
        """Load source neutral template mesh and all available ARKit blendshape delta meshes with canonical rotation."""
        if self._is_loaded:
            return True
            
        if not self.source_neutral_path.exists():
            print(f"[FacialBlendshapes] Warning: Source neutral mesh not found at {self.source_neutral_path}")
            return False
            
        try:
            self.source_neutral = trimesh.load(str(self.source_neutral_path), force='mesh', process=False)
            src_verts = np.asarray(self.source_neutral.vertices, dtype=np.float32)
            
            # Key anatomical reference landmarks computed from actual ARKit blendshape deltas:
            # - eyeBlinkLeft and eyeBlinkRight define the horizontal eye axis (+X)
            # - jawOpen and browInnerUp define the vertical face axis (+Y)
            p_blink_l = self.assets_dir / "eyeBlinkLeft.obj"
            p_blink_r = self.assets_dir / "eyeBlinkRight.obj"
            p_jaw = self.assets_dir / "jawOpen.obj"
            p_brow = self.assets_dir / "browInnerUp.obj"

            if p_blink_l.exists() and p_blink_r.exists() and p_jaw.exists() and p_brow.exists():
                m_bl = trimesh.load(str(p_blink_l), force='mesh', process=False)
                m_br = trimesh.load(str(p_blink_r), force='mesh', process=False)
                m_jaw = trimesh.load(str(p_jaw), force='mesh', process=False)
                m_brow = trimesh.load(str(p_brow), force='mesh', process=False)

                diff_bl = np.linalg.norm(np.asarray(m_bl.vertices, dtype=np.float32) - src_verts, axis=1)
                diff_br = np.linalg.norm(np.asarray(m_br.vertices, dtype=np.float32) - src_verts, axis=1)
                diff_jaw = np.linalg.norm(np.asarray(m_jaw.vertices, dtype=np.float32) - src_verts, axis=1)
                diff_brow = np.linalg.norm(np.asarray(m_brow.vertices, dtype=np.float32) - src_verts, axis=1)

                eye_l_c = src_verts[diff_bl > 1e-4].mean(axis=0)
                eye_r_c = src_verts[diff_br > 1e-4].mean(axis=0)
                jaw_c = src_verts[diff_jaw > 1e-4].mean(axis=0)
                brow_c = src_verts[diff_brow > 1e-4].mean(axis=0)

                # Right axis (+X) from character Right Eye to Left Eye (viewer right)
                right_vec = eye_l_c - eye_r_c
                right_vec /= np.linalg.norm(right_vec)

                # Up axis (+Y) from jaw to brow
                up_vec = brow_c - jaw_c
                up_vec = up_vec - np.dot(up_vec, right_vec) * right_vec
                up_vec /= np.linalg.norm(up_vec)

                # Front axis (+Z) = Right x Up
                front_vec = np.cross(right_vec, up_vec)
                front_vec /= np.linalg.norm(front_vec)

                self.R_align = np.stack([right_vec, up_vec, front_vec], axis=0).astype(np.float32)
            else:
                # Precomputed exact canonical rotation matrix for Neutral.obj
                self.R_align = np.array([
                    [-0.7068854,   0.70732665, -0.00147082],
                    [-0.33460304, -0.33256087,  0.88172793],
                    [ 0.6231805,   0.6237727,   0.471756  ]
                ], dtype=np.float32)
            
            # Canonical rotated template vertices (centered at origin)
            rot_src_verts = src_verts @ self.R_align.T
            rot_center = rot_src_verts.mean(axis=0)
            self.canonical_src_verts = (rot_src_verts - rot_center).astype(np.float32)
            
            # Load only eye and eyebrow blendshapes from assets directory
            eye_bs_set = set(ARKIT_BLENDSHAPES)
            count = 0
            for bs_file in self.assets_dir.glob("*.obj"):
                bs_name = bs_file.stem
                if bs_name not in eye_bs_set:
                    continue
                try:
                    m = trimesh.load(str(bs_file), force='mesh', process=False)
                    if len(m.vertices) == len(src_verts):
                        raw_delta = np.asarray(m.vertices, dtype=np.float32) - src_verts
                        # Rotate delta into standard coordinate frame
                        rot_delta = (raw_delta @ self.R_align.T).astype(np.float32)
                        self.source_deltas[bs_name] = rot_delta
                        count += 1
                except Exception as e:
                    print(f"[FacialBlendshapes] Failed to load {bs_file.name}: {e}")
                    
            print(f"[FacialBlendshapes] Loaded {count} Eye & Brow ARKit template blendshapes.")

            # Locate real facial landmarks on the canonical template
            self.source_landmarks_3d = None
            try:
                from .face_landmark_align import locate_face_landmarks_3d
                tmpl_center = self.canonical_src_verts.mean(axis=0)
                tmpl_radius = float(np.linalg.norm(self.canonical_src_verts - tmpl_center, axis=1).max())
                self.source_landmarks_3d = locate_face_landmarks_3d(
                    self.canonical_src_verts, self.source_neutral.faces, tmpl_center, tmpl_radius
                )
                if self.source_landmarks_3d:
                    print(f"[FacialBlendshapes] Located {len(self.source_landmarks_3d)} landmark groups on template "
                          f"({list(self.source_landmarks_3d.keys())}).")
                else:
                    print("[FacialBlendshapes] Could not locate landmarks on template; "
                          "will fall back to bounding-sphere alignment for all targets.")
            except Exception as e:
                print(f"[FacialBlendshapes] Landmark detection unavailable: {e}")

            self._is_loaded = True
            return True
        except Exception as e:
            print(f"[FacialBlendshapes] Error loading template blendshapes: {e}")
            return False

    def transfer_blendshapes(
        self,
        vertices: np.ndarray,
        faces: np.ndarray,
        smoothing_iterations: int = 1,
        amplitude_boost: float = 1.35,
        uvs: Optional[np.ndarray] = None,
        base_color_texture: Optional[Any] = None,
        eye_regions: Optional[Any] = None
    ) -> Dict[str, np.ndarray]:
        """
        Transfers 52 ARKit facial blendshapes onto the target mesh.

        Args:
            vertices: (N, 3) target mesh vertices
            faces: (F, 3) target mesh triangles
            smoothing_iterations: Laplacian smoothing steps for target deltas
            amplitude_boost: Multiplier for blendshape amplitude to make expressions vivid
            uvs: (N, 2) target mesh UV coords (optional, improves landmark detection accuracy)
            base_color_texture: PIL Image texture matching `uvs` (optional, same purpose)
            eye_regions: an `EyeRegions` already resolved for this mesh (optional). Detecting
                eyes costs a 16-angle render sweep plus a face-parsing pass per view, so a
                caller that has already paid for it -- as the pipeline does, because the
                eyelid geometry has to be built before this runs -- passes the result in
                rather than having it recomputed. Its masks must match `vertices` in length.

        Returns:
            morph_targets: Dict[blendshape_name -> (N, 3) delta vector array]
        """
        if not self._is_loaded:
            if not self.load_templates():
                return {}
                
        N = len(vertices)
        if N == 0 or len(self.source_deltas) == 0:
            return {}
            
        t0 = time.time()
        
        # 1. Detect head region on target mesh (skeleton-guided if available)
        from .mesh_segmentation import detect_head_region
        head = detect_head_region(vertices, faces)
        if head is None:
            print("[FacialBlendshapes] No head region detected; skipping blendshape transfer.")
            return {}
        head_center, head_radius, head_mask = head.center, head.radius, head.mask
        head_indices = np.where(head_mask)[0]
            
        target_head_verts = vertices[head_indices]

        # 2. Align canonical source template onto the target head region.
        # Prefer a real similarity transform (rotation + scale + translation) fitted from
        # detected facial landmarks (eyes/mouth/nose/brows) on both meshes -- this is what
        # actually makes "mouthSmile" land on the mouth instead of wherever a naive
        # axis-aligned, non-rotated placement happens to put it. Falls back to the old
        # bounding-sphere heuristic (no rotation) if landmarks can't be found on either side.
        src_verts = self.canonical_src_verts
        rotation = np.eye(3, dtype=np.float32)

        from .face_landmark_align import sample_vertex_colors
        target_vertex_colors = sample_vertex_colors(vertices, faces, uvs, base_color_texture)

        target_landmarks = None
        if self.source_landmarks_3d:
            try:
                from .face_landmark_align import locate_face_landmarks_3d, compute_similarity_transform
                target_landmarks = locate_face_landmarks_3d(
                    vertices, faces, head_center, head_radius, vertex_colors=target_vertex_colors
                )
            except Exception as e:
                print(f"[FacialBlendshapes] Landmark-based alignment failed, using bounding-sphere fallback: {e}")

        if target_landmarks:
            common = sorted(set(self.source_landmarks_3d) & set(target_landmarks))
            if len(common) >= 3:
                src_pts = np.stack([self.source_landmarks_3d[c] for c in common])
                tgt_pts = np.stack([target_landmarks[c] for c in common])
                rotation, scale, translation = compute_similarity_transform(src_pts, tgt_pts)
                aligned_src_verts = (src_verts @ rotation.T) * scale + translation
                print(f"[FacialBlendshapes] Aligned template via {len(common)} detected landmarks ({common}).")

                # The initial head_center/head_radius came from a coarse geometry-only
                # estimate and can sit too high/small to cover the whole face (mouth/nose
                # sit lower than eyes/brows). Landmarks are ground truth for where the face
                # actually is, so re-derive the head region around them -- otherwise a
                # correctly-aligned mouth/jaw can end up excluded from target_head_verts and
                # silently produce zero displacement.
                landmark_center = tgt_pts.mean(axis=0)
                landmark_spread = float(np.linalg.norm(tgt_pts - landmark_center, axis=1).max())
                head_center = landmark_center.astype(np.float32)
                head_radius = max(head_radius, landmark_spread * 2.2)
                head_mask = np.linalg.norm(vertices - head_center, axis=1) <= head_radius
                head_indices = np.where(head_mask)[0]
                target_head_verts = vertices[head_indices]
            else:
                target_landmarks = None

        if not target_landmarks:
            src_min = src_verts.min(axis=0)
            src_max = src_verts.max(axis=0)
            src_size = np.maximum(src_max - src_min, 1e-6)

            tgt_min = target_head_verts.min(axis=0)
            tgt_max = target_head_verts.max(axis=0)
            tgt_size = np.maximum(tgt_max - tgt_min, 1e-6)

            # Scale factor from canonical source to target head
            scale = float(tgt_size[1] / src_size[1])

            # Place canonical template at target head center (no rotation available)
            aligned_src_verts = src_verts * scale + head_center

        # 2b. Locate the eye regions. `detect_eye_regions` returns None whenever the
        # evidence is not strong enough to be sure, and that None is honoured here: eye
        # blendshapes are skipped entirely rather than applied to a guessed region. A
        # guessed eye becomes an eyeBlink that folds the cheek, which is worse than a
        # character that simply cannot blink.
        eye_falloff: Dict[str, np.ndarray] = {}
        brow_falloff: Dict[str, np.ndarray] = {}
        if eye_regions is not None and len(eye_regions.left_mask) != N:
            print(f"[FacialBlendshapes] Ignoring supplied eye regions: masks cover "
                  f"{len(eye_regions.left_mask)} vertices, mesh has {N}.")
            eye_regions = None
        if eye_regions is None:
            try:
                from .eye_detection import detect_eye_regions
                eye_regions = detect_eye_regions(
                    vertices, faces, head, vertex_colors=target_vertex_colors
                )
            except Exception as e:
                print(f"[FacialBlendshapes] Eye detection unavailable: {e}")

        if eye_regions is not None:
            # The brows come out of the same face-parsing pass as the eyes. Without a
            # located brow the whole browDown/browOuterUp family lands wherever the
            # template's own brow happened to be placed by the alignment, which on a head
            # with a different brow ridge is the forehead or the eyelid.
            eyes = {"Left": eye_regions.left_mask, "Right": eye_regions.right_mask}
            brows = {side: mask for side, mask in
                     (("Left", eye_regions.left_brow_mask), ("Right", eye_regions.right_brow_mask))
                     if mask is not None and mask.any()}

            # Widen the head region to cover every located feature *before* measuring any
            # falloff: the falloff arrays are indexed by `target_head_verts`, so they have
            # to be built against its final extent.
            for mask in list(eyes.values()) + list(brows.values()):
                head_mask = head_mask | mask
            head_indices = np.where(head_mask)[0]
            target_head_verts = vertices[head_indices]

            # Feather over a fraction of the distance between the eyes, so the falloff
            # scales with the character's own face rather than an absolute distance.
            margin = max(eye_regions.separation * 0.45, head_radius * 0.10)

            def feather(mask: np.ndarray) -> np.ndarray:
                d, _ = cKDTree(vertices[mask]).query(target_head_verts, k=1)
                w = np.clip(1.0 - d / margin, 0.0, 1.0)
                return (w * w * (3.0 - 2.0 * w)).astype(np.float32)

            for suffix, mask in eyes.items():
                eye_falloff[suffix] = feather(mask)
            for suffix, mask in brows.items():
                brow_falloff[suffix] = feather(mask)

        # 3. Build spatial KDTree for fast KNN correspondence mapping
        tree = cKDTree(aligned_src_verts)
        k_neighbors = 4
        dists, indices = tree.query(target_head_verts, k=k_neighbors)
        dists = np.maximum(dists, 1e-6)
        weights = 1.0 / (dists ** 2)
        weights /= weights.sum(axis=1, keepdims=True)  # (M, k)
        
        # 4. Compute smooth spatial falloff weights (Gaussian feathering at neck/perimeter)
        dists_to_center = np.linalg.norm(target_head_verts - head_center, axis=1)
        r_inner = head_radius * 0.50
        r_outer = head_radius * 0.95
        
        falloff = np.clip((r_outer - dists_to_center) / max(r_outer - r_inner, 1e-6), 0.0, 1.0)
        falloff = falloff * falloff * (3.0 - 2.0 * falloff)  # Cubic smoothstep (M,)
        
        # 5. Build vertex neighbor adjacency for Laplacian delta smoothing
        adj: Dict[int, List[int]] = {i: [] for i in range(len(head_indices))}
        head_idx_map = {global_idx: local_idx for local_idx, global_idx in enumerate(head_indices)}
        for f in faces:
            h0, h1, h2 = head_idx_map.get(f[0]), head_idx_map.get(f[1]), head_idx_map.get(f[2])
            if h0 is not None and h1 is not None:
                adj[h0].append(h1)
                adj[h1].append(h0)
            if h1 is not None and h2 is not None:
                adj[h1].append(h2)
                adj[h2].append(h1)
            if h2 is not None and h0 is not None:
                adj[h2].append(h0)
                adj[h0].append(h2)
                
        # 6. Transfer all 52 ARKit blendshapes
        morph_targets: Dict[str, np.ndarray] = {}
        
        total_scale = scale * amplitude_boost
        # Eye-family blendshapes need to know where the eyes actually are. Without either
        # a detected eye region or a detected pair of eye landmarks, the template lands by
        # a bounding-sphere guess, and an eyeBlink placed by guesswork deforms whatever
        # happens to sit there. Skip them instead.
        eyes_located = eye_regions is not None or (
            target_landmarks is not None
            and "left_eye" in target_landmarks and "right_eye" in target_landmarks
        )
        if not eyes_located:
            print("[FacialBlendshapes] Eyes not located; skipping eye blendshapes.")

        for bs_name, src_delta in self.source_deltas.items():
            if bs_name.startswith("eye") and not eyes_located:
                continue

            # Interpolate canonical source delta onto target head vertices
            # src_delta: (3084, 3) rotated into standard Y-Up Z-Front space; apply the same
            # rotation used to align the template positions so delta *directions* stay correct
            k_deltas = (src_delta[indices] @ rotation.T) * total_scale  # (M, k, 3)
            tgt_head_delta = np.sum(k_deltas * weights[:, :, None], axis=1)  # (M, 3)
            
            # Apply Laplacian smoothing over head mesh topology
            if smoothing_iterations > 0:
                for _ in range(smoothing_iterations):
                    smooth_delta = tgt_head_delta.copy()
                    for loc_i, nbrs in adj.items():
                        if len(nbrs) > 0:
                            smooth_delta[loc_i] = 0.7 * tgt_head_delta[loc_i] + 0.3 * tgt_head_delta[nbrs].mean(axis=0)
                    tgt_head_delta = smooth_delta
                    
            # Apply feathering falloff so boundary blends to 0 displacement
            tgt_head_delta *= falloff[:, None]

            # Constrain side-specific blendshapes to the region they belong to, if found.
            # `browInnerUp` carries no side suffix -- it is one bilateral shape spanning
            # both brows -- so it matches nothing here and stays unconstrained, which is
            # correct: clamping it to one side would pull only half of it.
            region = (eye_falloff if bs_name.startswith("eye")
                      else brow_falloff if bs_name.startswith("brow") else None)
            if region:
                for suffix, w in region.items():
                    if bs_name.endswith(suffix):
                        tgt_head_delta *= w[:, None]
                        break

            # Place into full mesh delta array of size (N, 3)
            full_delta = np.zeros((N, 3), dtype=np.float32)
            full_delta[head_indices] = tgt_head_delta.astype(np.float32)

            # 7. Adaptive Full-Closure Eyelid Scaling for Anime / Chibi / Big-Eyed Characters
            # In human templates, eyelids travel ~1.5cm down, which on huge cartoon/chibi eyes (10-15cm tall)
            # only squints 10% instead of fully shutting the eyelid. We detect the actual eye height
            # and scale vertical travel so the upper eyelid fully reaches the lower eyelid when weight=1.0.
            if bs_name.startswith("eye"):
                disp_mag = np.linalg.norm(full_delta, axis=1)
                active_idx = np.where(disp_mag > 1e-4)[0]
                if len(active_idx) > 0:
                    # Clean up spurious distant movements (eliminate leakage onto turtle shell, neck, or body)
                    eye_center_est = vertices[active_idx].mean(axis=0)
                    eye_dist = np.linalg.norm(vertices[active_idx] - eye_center_est, axis=1)
                    max_allowed_r = min(head_radius * 0.75, 0.12)
                    spurious = active_idx[eye_dist > max_allowed_r]
                    if len(spurious) > 0:
                        full_delta[spurious] = 0.0

                    # Re-calculate on valid eye vertices
                    valid_idx = np.where(np.linalg.norm(full_delta, axis=1) > 1e-4)[0]
                    if len(valid_idx) > 0 and bs_name in ("eyeBlinkLeft", "eyeBlinkRight", "eyeSquintLeft", "eyeSquintRight"):
                        eye_pts = vertices[valid_idx]
                        y_min, y_max = float(eye_pts[:, 1].min()), float(eye_pts[:, 1].max())
                        eye_h = max(y_max - y_min, 1e-4)
                        cur_max = float(np.linalg.norm(full_delta[valid_idx], axis=1).max())

                        target_close_h = eye_h * (0.85 if "Blink" in bs_name else 0.40)
                        if cur_max < target_close_h and cur_max > 1e-5:
                            scale_factor = target_close_h / cur_max
                            full_delta[valid_idx, 1] *= scale_factor
                            full_delta[valid_idx, 2] += np.abs(full_delta[valid_idx, 1]) * 0.12

            if np.abs(full_delta).max() > 1e-5:
                morph_targets[bs_name] = full_delta

        # The eye family is no longer built here. Every shape that used to live in this
        # spot displaced the painted eye's own vertices, and a displacement field applied to
        # a painted circle produces an ellipse -- the pupil tore out of shape on every one
        # of them. `pipeline.eyelid_patch` now supplies eyeBlink / eyeSquint / eyeWide and
        # the whole eyeLook family from geometry that either moves rigidly (the iris cap) or
        # is not part of the eye at all (the lids, the surrounding skin). The caller masks
        # this function's output over that geometry before merging the two.

        elapsed = time.time() - t0
        print(f"[FacialBlendshapes] Successfully transferred {len(morph_targets)} ARKit blendshapes in {elapsed:.2f}s (head vertices: {len(head_indices)}/{N})")
        return morph_targets
