"""
Facial Blendshapes Generation via Deformation Transfer (ARKit 52 Blendshapes)

Transfers 52 standard Apple ARKit facial blendshapes from template meshes onto arbitrary
target 3D character/head meshes generated by TRELLIS.2, Hunyuan3D, or uploaded by user.
Produces glTF 2.0 morph targets compatible with Three.js, Unreal Engine, Unity, Blender,
and Apple ARKit / FaceID tracking.

A shape is transferred by fitting the template onto the target head and then reading the
template's displacement field at each target vertex through that fit. The fit runs in the
two stages `flame-fitting/fit_lmk3d.py` uses -- rigid first, then non-rigid under a
regulariser -- driven by dense landmarks embedded barycentrically on the template. See
`pipeline/template_fit.py`.

Reference:
- vasiliskatr/deformation_transfer_ARkit_blendshapes (MIT License)
- Amberg et al.: Optimal Step Nonrigid ICP Algorithms for Surface Registration (CVPR 2007)
- Rubikplayer/flame-fitting, yfeng95/DECA -- for the fitting structure and the barycentric
  landmark embedding. Method only: both carry a non-commercial MPG licence, so no code
  from either is used here.

Not Sumner & Popović (SIGGRAPH 2004), which this file used to cite: that method solves a
least-squares system for the target's vertex positions from per-triangle deformation
gradients. It earns its cost on shapes with large rotation -- jawOpen, mouthSmile -- and
those are not in this file's scope, which is the 19 eye and brow shapes.
"""

import os
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any

import numpy as np
import trimesh
from scipy.spatial import cKDTree


# Standard Apple ARKit eye and eyebrow blendshapes (Focused purely on eye expressions)
ARKIT_BLENDSHAPES = [
    # Eye Blinks (Nháy mắt / Nhắm mắt)
    "eyeBlinkLeft", "eyeBlinkRight",
    # Eye Squints (Nheo mắt / Híp mắt)
    "eyeSquintLeft", "eyeSquintRight",
    # Eye Wide (Mở to mắt / Trố mắt)
    "eyeWideLeft", "eyeWideRight",
    # Eye Gaze / Look Directions (Hướng nhìn / Đảo mắt)
    "eyeLookUpLeft", "eyeLookUpRight",
    "eyeLookDownLeft", "eyeLookDownRight",
    "eyeLookInLeft", "eyeLookInRight",
    "eyeLookOutLeft", "eyeLookOutRight",
    # Eyebrows (Nhíu mày / Nhướn mày)
    "browDownLeft", "browDownRight",
    "browInnerUp", "browOuterUpLeft", "browOuterUpRight"
]

EXPRESSION_PRESETS = {
    "wink_right": {
        "name": "Nháy mắt phải (Wink Right)",
        "icon": "😉",
        "weights": {
            "eyeBlinkRight": 1.0,
            "eyeSquintRight": 0.3
        }
    },
    "wink_left": {
        "name": "Nháy mắt trái (Wink Left)",
        "icon": "😜",
        "weights": {
            "eyeBlinkLeft": 1.0,
            "eyeSquintLeft": 0.3
        }
    },
    "blink": {
        "name": "Nhắm 2 mắt (Blink Both)",
        "icon": "😌",
        "weights": {
            "eyeBlinkLeft": 1.0,
            "eyeBlinkRight": 1.0
        }
    },
    "squint": {
        "name": "Nheo mắt (Squint Eyes)",
        "icon": "🧐",
        "weights": {
            "eyeSquintLeft": 0.85,
            "eyeSquintRight": 0.85
        }
    },
    "wide": {
        "name": "Mở to mắt (Wide Eyes)",
        "icon": "😳",
        "weights": {
            "eyeWideLeft": 1.0,
            "eyeWideRight": 1.0,
            "browInnerUp": 0.7
        }
    },
    "frown": {
        "name": "Nhíu mắt / Cau có (Frown Eyes)",
        "icon": "😠",
        "weights": {
            "browDownLeft": 1.0,
            "browDownRight": 1.0,
            "eyeSquintLeft": 0.5,
            "eyeSquintRight": 0.5
        }
    },
    "look_up": {
        "name": "Đảo mắt lên (Look Up)",
        "icon": "🙄",
        "weights": {
            "eyeLookUpLeft": 0.9,
            "eyeLookUpRight": 0.9,
            "browInnerUp": 0.4
        }
    },
    "look_left": {
        "name": "Liếc mắt trái (Look Left)",
        "icon": "👈",
        "weights": {
            "eyeLookInRight": 0.85,
            "eyeLookOutLeft": 0.85
        }
    },
    "look_right": {
        "name": "Liếc mắt phải (Look Right)",
        "icon": "👉",
        "weights": {
            "eyeLookInLeft": 0.85,
            "eyeLookOutRight": 0.85
        }
    }
}



class FacialBlendshapesTransfer:
    """
    Deformation Transfer engine that maps 52 ARKit facial blendshapes onto arbitrary target 3D meshes.
    """

    def __init__(self, assets_dir: Optional[str] = None):
        if assets_dir is None:
            assets_dir = str(Path(__file__).resolve().parent / "assets" / "arkit_blendshapes")
        
        self.assets_dir = Path(assets_dir)
        self.source_neutral_path = self.assets_dir / "Neutral.obj"
        
        self.source_neutral: Optional[trimesh.Trimesh] = None
        self.source_deltas: Dict[str, np.ndarray] = {}
        self.src_faces: Optional[np.ndarray] = None
        self.R_align: np.ndarray = np.eye(3, dtype=np.float32)
        self.source_landmarks_3d: Optional[Dict[str, np.ndarray]] = None
        # Dense landmark embedding on the canonical template, in the (face index,
        # barycentric weights) form `flame-fitting` keeps in `flame_static_embedding.pkl`.
        self.lmk_indices: Optional[np.ndarray] = None
        self.lmk_face_idx: Optional[np.ndarray] = None
        self.lmk_bary: Optional[np.ndarray] = None
        self._is_loaded = False
        
    def load_templates(self) -> bool:
        """Load source neutral template mesh and all available ARKit blendshape delta meshes with canonical rotation."""
        if self._is_loaded:
            return True
            
        if not self.source_neutral_path.exists():
            print(f"[FacialBlendshapes] Warning: Source neutral mesh not found at {self.source_neutral_path}")
            return False
            
        try:
            self.source_neutral = trimesh.load(str(self.source_neutral_path), force='mesh', process=False)
            src_verts = np.asarray(self.source_neutral.vertices, dtype=np.float32)
            
            # Key anatomical reference landmarks computed from actual ARKit blendshape deltas:
            # - eyeBlinkLeft and eyeBlinkRight define the horizontal eye axis (+X)
            # - jawOpen and browInnerUp define the vertical face axis (+Y)
            p_blink_l = self.assets_dir / "eyeBlinkLeft.obj"
            p_blink_r = self.assets_dir / "eyeBlinkRight.obj"
            p_jaw = self.assets_dir / "jawOpen.obj"
            p_brow = self.assets_dir / "browInnerUp.obj"

            if p_blink_l.exists() and p_blink_r.exists() and p_jaw.exists() and p_brow.exists():
                m_bl = trimesh.load(str(p_blink_l), force='mesh', process=False)
                m_br = trimesh.load(str(p_blink_r), force='mesh', process=False)
                m_jaw = trimesh.load(str(p_jaw), force='mesh', process=False)
                m_brow = trimesh.load(str(p_brow), force='mesh', process=False)

                diff_bl = np.linalg.norm(np.asarray(m_bl.vertices, dtype=np.float32) - src_verts, axis=1)
                diff_br = np.linalg.norm(np.asarray(m_br.vertices, dtype=np.float32) - src_verts, axis=1)
                diff_jaw = np.linalg.norm(np.asarray(m_jaw.vertices, dtype=np.float32) - src_verts, axis=1)
                diff_brow = np.linalg.norm(np.asarray(m_brow.vertices, dtype=np.float32) - src_verts, axis=1)

                eye_l_c = src_verts[diff_bl > 1e-4].mean(axis=0)
                eye_r_c = src_verts[diff_br > 1e-4].mean(axis=0)
                jaw_c = src_verts[diff_jaw > 1e-4].mean(axis=0)
                brow_c = src_verts[diff_brow > 1e-4].mean(axis=0)

                # Right axis (+X) from character Right Eye to Left Eye (viewer right)
                right_vec = eye_l_c - eye_r_c
                right_vec /= np.linalg.norm(right_vec)

                # Up axis (+Y) from jaw to brow
                up_vec = brow_c - jaw_c
                up_vec = up_vec - np.dot(up_vec, right_vec) * right_vec
                up_vec /= np.linalg.norm(up_vec)

                # Front axis (+Z) = Right x Up
                front_vec = np.cross(right_vec, up_vec)
                front_vec /= np.linalg.norm(front_vec)

                self.R_align = np.stack([right_vec, up_vec, front_vec], axis=0).astype(np.float32)
            else:
                # Precomputed exact canonical rotation matrix for Neutral.obj
                self.R_align = np.array([
                    [-0.7068854,   0.70732665, -0.00147082],
                    [-0.33460304, -0.33256087,  0.88172793],
                    [ 0.6231805,   0.6237727,   0.471756  ]
                ], dtype=np.float32)
            
            # Canonical rotated template vertices (centered at origin)
            rot_src_verts = src_verts @ self.R_align.T
            rot_center = rot_src_verts.mean(axis=0)
            self.canonical_src_verts = (rot_src_verts - rot_center).astype(np.float32)
            
            # Load only eye and eyebrow blendshapes from assets directory
            eye_bs_set = set(ARKIT_BLENDSHAPES)
            count = 0
            for bs_file in self.assets_dir.glob("*.obj"):
                bs_name = bs_file.stem
                if bs_name not in eye_bs_set:
                    continue
                try:
                    m = trimesh.load(str(bs_file), force='mesh', process=False)
                    if len(m.vertices) == len(src_verts):
                        raw_delta = np.asarray(m.vertices, dtype=np.float32) - src_verts
                        # Rotate delta into standard coordinate frame
                        rot_delta = (raw_delta @ self.R_align.T).astype(np.float32)
                        self.source_deltas[bs_name] = rot_delta
                        count += 1
                except Exception as e:
                    print(f"[FacialBlendshapes] Failed to load {bs_file.name}: {e}")
                    
            print(f"[FacialBlendshapes] Loaded {count} Eye & Brow ARKit template blendshapes.")

            self._weld_template()
            self._load_landmark_embedding()

            self._is_loaded = True
            return True
        except Exception as e:
            print(f"[FacialBlendshapes] Error loading template blendshapes: {e}")
            return False

    def _weld_template(self) -> None:
        """
        Merges the template's duplicated vertices and rewrites the faces and deltas
        against the merged indexing.

        `Neutral.obj` stores 3084 vertices for 1220 distinct positions -- one copy per
        face corner, the usual result of an OBJ carrying per-face normals. Indexed that
        way *no two faces share an edge*, so the mesh is, as far as any topological
        operation is concerned, 2304 loose triangles. The stiffness term of the non-rigid
        fit is defined over edges between neighbouring vertices, and on a loose-triangle
        graph it cannot couple anything: every triangle would be free to fly off on its
        own. Welding first is what makes the regulariser mean what it says.
        """
        verts = self.canonical_src_verts
        unique, inverse = np.unique(verts, axis=0, return_inverse=True)
        inverse = inverse.reshape(-1)

        faces = inverse[np.asarray(self.source_neutral.faces)]
        # Drop faces that collapsed to a degenerate triangle during the merge.
        faces = faces[(faces[:, 0] != faces[:, 1])
                      & (faces[:, 1] != faces[:, 2])
                      & (faces[:, 2] != faces[:, 0])]

        counts = np.bincount(inverse, minlength=len(unique)).astype(np.float32)
        welded_deltas = {}
        for name, delta in self.source_deltas.items():
            summed = np.zeros((len(unique), 3), dtype=np.float32)
            np.add.at(summed, inverse, delta)
            welded_deltas[name] = summed / counts[:, None]

        self.canonical_src_verts = unique.astype(np.float32)
        self.src_faces = faces.astype(np.int64)
        self.source_deltas = welded_deltas
        print(f"[FacialBlendshapes] Welded template: {len(verts)} -> {len(unique)} vertices, "
              f"{len(faces)} faces.")

    def _load_landmark_embedding(self) -> None:
        """
        Locates MediaPipe's landmarks on the canonical template and stores each one as a
        triangle index plus barycentric weights.

        This is the template side of the correspondence, and it never changes, so it is
        detected once and cached next to the template meshes. Storing a landmark as a
        point *on a triangle* rather than as the nearest vertex is what `flame-fitting`
        does with `lmk_face_idx` / `lmk_b_coords`: it is accurate below the template's
        vertex spacing, and it keeps the landmark term linear in the fit's unknowns.
        """
        import hashlib

        cache_path = self.assets_dir / "lmk_embedding.npz"
        digest = hashlib.sha1(self.canonical_src_verts.tobytes()).hexdigest()

        if cache_path.exists():
            try:
                cached = np.load(cache_path, allow_pickle=True)
                if str(cached["digest"]) == digest:
                    self.lmk_indices = cached["indices"]
                    self.lmk_face_idx = cached["face_idx"]
                    self.lmk_bary = cached["bary"]
                    self.source_landmarks_3d = {
                        str(k): v for k, v in cached["groups"].item().items()
                    }
                    print(f"[FacialBlendshapes] Loaded cached landmark embedding "
                          f"({len(self.lmk_indices)} points).")
                    return
            except Exception as e:
                print(f"[FacialBlendshapes] Ignoring unreadable landmark cache: {e}")

        try:
            from .face_landmark_align import detect_face_landmarks

            tmpl_center = self.canonical_src_verts.mean(axis=0)
            tmpl_radius = float(np.linalg.norm(
                self.canonical_src_verts - tmpl_center, axis=1).max())
            found = detect_face_landmarks(
                self.canonical_src_verts, self.src_faces, tmpl_center, tmpl_radius
            )
        except Exception as e:
            print(f"[FacialBlendshapes] Landmark detection unavailable: {e}")
            return

        if found is None:
            print("[FacialBlendshapes] Could not locate landmarks on template; "
                  "will fall back to bounding-sphere alignment for all targets.")
            return

        self.source_landmarks_3d = found.groups

        tmpl_mesh = trimesh.Trimesh(vertices=self.canonical_src_verts,
                                    faces=self.src_faces, process=False)
        closest, _, tri_id = trimesh.proximity.closest_point(tmpl_mesh, found.dense_points)
        bary = trimesh.triangles.points_to_barycentric(
            tmpl_mesh.triangles[tri_id], closest)

        self.lmk_indices = found.dense_indices
        self.lmk_face_idx = tri_id.astype(np.int64)
        self.lmk_bary = bary.astype(np.float64)

        try:
            np.savez(cache_path, digest=digest, indices=self.lmk_indices,
                     face_idx=self.lmk_face_idx, bary=self.lmk_bary,
                     groups=np.array(found.groups, dtype=object))
        except Exception as e:
            print(f"[FacialBlendshapes] Could not cache landmark embedding: {e}")

        print(f"[FacialBlendshapes] Embedded {len(self.lmk_indices)} template landmarks "
              f"({len(found.groups)} feature groups).")

    def _template_landmark_points(self) -> np.ndarray:
        """Evaluates the embedded landmarks on the canonical template."""
        tri = self.src_faces[self.lmk_face_idx]
        return np.einsum('lkj,lk->lj', self.canonical_src_verts[tri], self.lmk_bary)

    def _fit_template(
        self,
        src_verts: np.ndarray,
        src_faces: np.ndarray,
        vertices: np.ndarray,
        faces: np.ndarray,
        head_indices: np.ndarray,
        found,
        fallback_src: np.ndarray,
        fallback_tgt: np.ndarray,
        compute_similarity_transform,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Fits the canonical template onto the target head in the two stages
        `flame-fitting/fit_lmk3d.py` uses, and returns the fitted template vertices
        together with the per-vertex linear transform that carries a template-space
        displacement onto the fitted surface.

        Stage 1 solves rotation, uniform scale and translation only. Stage 2 opens up a
        per-vertex affine under a stiffness regulariser. Stage 2 is discarded whenever it
        does not measurably beat stage 1, so a character MediaPipe mislabels degrades to
        the rigid placement instead of to a warped one.
        """
        from .template_fit import nonrigid_icp, robust_similarity

        n_src = len(src_verts)

        # --- stage 1: rigid + uniform scale -----------------------------------------
        dense_ok = (self.lmk_indices is not None and found is not None
                    and len(found.dense_indices) > 0)
        if dense_ok:
            order = {int(li): k for k, li in enumerate(found.dense_indices)}
            keep = np.array([k for k, li in enumerate(self.lmk_indices)
                             if int(li) in order], dtype=np.int64)
            dense_ok = len(keep) >= 8

        if dense_ok:
            tgt_rows = np.array([order[int(self.lmk_indices[k])] for k in keep], dtype=np.int64)
            src_lmk = self._template_landmark_points()[keep]
            tgt_lmk = found.dense_points[tgt_rows].astype(np.float64)
            rotation, scale, translation = robust_similarity(src_lmk, tgt_lmk)
            source = f"{len(keep)} dense landmarks"
        else:
            rotation, scale, translation = compute_similarity_transform(fallback_src, fallback_tgt)
            src_lmk = tgt_lmk = None
            source = f"{len(fallback_src)} feature-group centroids"

        aligned = (src_verts @ rotation.T) * scale + translation
        rigid_transform = (rotation * scale).astype(np.float32)
        rigid_stack = np.broadcast_to(rigid_transform, (n_src, 3, 3)).copy()

        rigid_rms = float('nan')
        if src_lmk is not None:
            fitted_lmk = (src_lmk @ rotation.T) * scale + translation
            rigid_rms = float(np.sqrt(((fitted_lmk - tgt_lmk) ** 2).sum(axis=1).mean()))
        print(f"[FacialBlendshapes] Stage 1 (rigid) aligned template via {source}"
              + (f", landmark RMS {rigid_rms:.5f}." if src_lmk is not None else "."))

        if not dense_ok:
            return aligned.astype(np.float32), rigid_stack

        # --- stage 2: non-rigid ------------------------------------------------------
        head_mask = np.zeros(len(vertices), dtype=bool)
        head_mask[head_indices] = True
        sub_map = np.full(len(vertices), -1, dtype=np.int64)
        sub_map[head_indices] = np.arange(len(head_indices))
        face_keep = head_mask[faces].all(axis=1)
        sub_faces = sub_map[faces[face_keep]]
        if len(sub_faces) < 16:
            print("[FacialBlendshapes] Head region has too few faces for a non-rigid fit; "
                  "keeping the rigid alignment.")
            return aligned.astype(np.float32), rigid_stack

        # The landmark embedding lives on the canonical template, and stage 2 starts from
        # the stage-1 result, so the embedding is re-evaluated on the aligned vertices.
        try:
            fit = nonrigid_icp(
                src_vertices=aligned,
                src_faces=src_faces,
                tgt_vertices=vertices[head_indices],
                tgt_faces=sub_faces,
                src_lmk_face_idx=self.lmk_face_idx[keep],
                src_lmk_bary=self.lmk_bary[keep],
                tgt_lmk_points=tgt_lmk,
            )
        except Exception as e:
            print(f"[FacialBlendshapes] Non-rigid fit failed ({e}); keeping rigid alignment.")
            return aligned.astype(np.float32), rigid_stack

        # Guard rails. A landmark set that is wrong in a way the robustifier could not
        # absorb makes stage 2 actively worse than stage 1, and an unbounded per-vertex
        # affine turns that into a warped face rather than a merely misplaced one.
        # `nonrigid_icp` was handed the stage-1 result, so its transforms describe the
        # deformation *on top of* the rigid alignment and an undistorted fit leaves them at
        # the identity. Comparing them against the rigid transform instead -- which carries
        # the template's own units, about 256 against a target's 0.17 -- made this ratio
        # read 366 on every real character and threw stage 2 away every time.
        ratio = np.linalg.norm(fit.transforms, axis=(1, 2)) / np.sqrt(3.0)
        if not np.isfinite(fit.landmark_rms) or fit.landmark_rms > rigid_rms:
            print(f"[FacialBlendshapes] Non-rigid fit did not improve on rigid "
                  f"(RMS {fit.landmark_rms:.5f} vs {rigid_rms:.5f}); keeping rigid alignment.")
            return aligned.astype(np.float32), rigid_stack
        if float(ratio.min()) < 0.3 or float(ratio.max()) > 3.0:
            print(f"[FacialBlendshapes] Non-rigid fit distorted the template "
                  f"(local scale {ratio.min():.2f}-{ratio.max():.2f}); keeping rigid alignment.")
            return aligned.astype(np.float32), rigid_stack

        print(f"[FacialBlendshapes] Stage 2 (non-rigid) landmark RMS {fit.landmark_rms:.5f} "
              f"(from {rigid_rms:.5f}).")
        # `fit.transforms` maps displacements defined on `aligned`, which already carries
        # the stage-1 rotation and scale, so the two compose.
        return fit.vertices, (fit.transforms @ rigid_transform).astype(np.float32)

    def transfer_blendshapes(
        self,
        vertices: np.ndarray,
        faces: np.ndarray,
        amplitude_boost: float = 1.0,
        uvs: Optional[np.ndarray] = None,
        base_color_texture: Optional[Any] = None,
        eye_regions: Optional[Any] = None,
        protected: Optional[np.ndarray] = None
    ) -> Dict[str, np.ndarray]:
        """
        Transfers 52 ARKit facial blendshapes onto the target mesh.

        Args:
            vertices: (N, 3) target mesh vertices
            faces: (F, 3) target mesh triangles
            amplitude_boost: Multiplier for blendshape amplitude. Defaults to 1.0 -- the
                fitted per-vertex transforms already carry the target's own scale, so a
                boost is no longer needed to undo a smoothing pass that no longer exists.
            uvs: (N, 2) target mesh UV coords (optional, improves landmark detection accuracy)
            base_color_texture: PIL Image texture matching `uvs` (optional, same purpose)
            eye_regions: an `EyeRegions` already resolved for this mesh (optional). Detecting
                eyes costs a 16-angle render sweep plus a face-parsing pass per view, so a
                caller that has already paid for it -- as the pipeline does, because the
                eyelid geometry has to be built before this runs -- passes the result in
                rather than having it recomputed. Its masks must match `vertices` in length.
            protected: (N,) boolean mask of geometry owned by `pipeline.eyelid_patch` --
                the painted eye, the lids, the iris caps. Every eye-family displacement is
                faded to zero *on* this region and back up outside it, because the caller
                zeroes it there anyway; without the fade the surrounding skin would move
                at full amplitude right against skin that cannot move at all.

        Returns:
            morph_targets: Dict[blendshape_name -> (N, 3) delta vector array]
        """
        if not self._is_loaded:
            if not self.load_templates():
                return {}
                
        N = len(vertices)
        if N == 0 or len(self.source_deltas) == 0:
            return {}
            
        t0 = time.time()
        
        # 1. Detect head region on target mesh (skeleton-guided if available)
        from .mesh_segmentation import detect_head_region, weld_groups
        head = detect_head_region(vertices, faces)
        if head is None:
            print("[FacialBlendshapes] No head region detected; skipping blendshape transfer.")
            return {}
        head_center, head_radius, head_mask = head.center, head.radius, head.mask
        head_indices = np.where(head_mask)[0]
            
        target_head_verts = vertices[head_indices]

        # 2. Align canonical source template onto the target head region.
        # Prefer a real similarity transform (rotation + scale + translation) fitted from
        # detected facial landmarks (eyes/mouth/nose/brows) on both meshes -- this is what
        # actually makes "mouthSmile" land on the mouth instead of wherever a naive
        # axis-aligned, non-rotated placement happens to put it. Falls back to the old
        # bounding-sphere heuristic (no rotation) if landmarks can't be found on either side.
        src_verts = self.canonical_src_verts
        src_faces = self.src_faces

        from .face_landmark_align import sample_vertex_colors
        target_vertex_colors = sample_vertex_colors(vertices, faces, uvs, base_color_texture)

        found = None
        if self.source_landmarks_3d:
            try:
                from .face_landmark_align import detect_face_landmarks
                found = detect_face_landmarks(
                    vertices, faces, head_center, head_radius, vertex_colors=target_vertex_colors
                )
            except Exception as e:
                print(f"[FacialBlendshapes] Landmark detection failed, using bounding-sphere fallback: {e}")

        target_landmarks = found.groups if found is not None else None
        if target_landmarks is not None and len(target_landmarks) < 3:
            target_landmarks = None

        if target_landmarks:
            from .face_landmark_align import compute_similarity_transform
            common = sorted(set(self.source_landmarks_3d) & set(target_landmarks))
            src_pts = np.stack([self.source_landmarks_3d[c] for c in common])
            tgt_pts = np.stack([target_landmarks[c] for c in common])

            # The initial head_center/head_radius came from a coarse geometry-only
            # estimate and can sit too high/small to cover the whole face (mouth/nose
            # sit lower than eyes/brows). Landmarks are ground truth for where the face
            # actually is, so re-derive the head region around them -- otherwise a
            # correctly-aligned mouth/jaw can end up excluded from target_head_verts and
            # silently produce zero displacement.
            landmark_center = tgt_pts.mean(axis=0)
            landmark_spread = float(np.linalg.norm(tgt_pts - landmark_center, axis=1).max())
            head_center = landmark_center.astype(np.float32)
            head_radius = max(head_radius, landmark_spread * 2.2)
            head_mask = np.linalg.norm(vertices - head_center, axis=1) <= head_radius
            head_indices = np.where(head_mask)[0]
            target_head_verts = vertices[head_indices]

            aligned_src_verts, vertex_transforms = self._fit_template(
                src_verts, src_faces, vertices, faces, head_indices, found,
                fallback_src=src_pts, fallback_tgt=tgt_pts,
                compute_similarity_transform=compute_similarity_transform)
        else:
            src_min = src_verts.min(axis=0)
            src_max = src_verts.max(axis=0)
            src_size = np.maximum(src_max - src_min, 1e-6)

            tgt_min = target_head_verts.min(axis=0)
            tgt_max = target_head_verts.max(axis=0)
            tgt_size = np.maximum(tgt_max - tgt_min, 1e-6)

            # Scale factor from canonical source to target head
            scale = float(tgt_size[1] / src_size[1])

            # Place canonical template at target head center (no rotation available)
            aligned_src_verts = src_verts * scale + head_center
            vertex_transforms = np.broadcast_to(
                np.eye(3, dtype=np.float32) * scale, (len(src_verts), 3, 3)).copy()

        # 2b. Locate the eye regions. `detect_eye_regions` returns None whenever the
        # evidence is not strong enough to be sure, and that None is honoured here: eye
        # blendshapes are skipped entirely rather than applied to a guessed region. A
        # guessed eye becomes an eyeBlink that folds the cheek, which is worse than a
        # character that simply cannot blink.
        eye_falloff: Dict[str, np.ndarray] = {}
        feather_margin = 0.0
        brow_falloff: Dict[str, np.ndarray] = {}
        if eye_regions is not None and len(eye_regions.left_mask) != N:
            print(f"[FacialBlendshapes] Ignoring supplied eye regions: masks cover "
                  f"{len(eye_regions.left_mask)} vertices, mesh has {N}.")
            eye_regions = None
        if eye_regions is None:
            try:
                from .eye_detection import detect_eye_regions
                eye_regions = detect_eye_regions(
                    vertices, faces, head, vertex_colors=target_vertex_colors
                )
            except Exception as e:
                print(f"[FacialBlendshapes] Eye detection unavailable: {e}")

        if eye_regions is not None:
            # The brows come out of the same face-parsing pass as the eyes. Without a
            # located brow the whole browDown/browOuterUp family lands wherever the
            # template's own brow happened to be placed by the alignment, which on a head
            # with a different brow ridge is the forehead or the eyelid.
            eyes = {"Left": eye_regions.left_mask, "Right": eye_regions.right_mask}
            brows = {side: mask for side, mask in
                     (("Left", eye_regions.left_brow_mask), ("Right", eye_regions.right_brow_mask))
                     if mask is not None and mask.any()}

            # Widen the head region to cover every located feature *before* measuring any
            # falloff: the falloff arrays are indexed by `target_head_verts`, so they have
            # to be built against its final extent.
            for mask in list(eyes.values()) + list(brows.values()):
                head_mask = head_mask | mask
            head_indices = np.where(head_mask)[0]
            target_head_verts = vertices[head_indices]

            # Feather over a fraction of the distance between the eyes, so the falloff
            # scales with the character's own face rather than an absolute distance.
            margin = max(eye_regions.separation * 0.45, head_radius * 0.10)

            def feather(mask: np.ndarray) -> np.ndarray:
                d, _ = cKDTree(vertices[mask]).query(target_head_verts, k=1)
                w = np.clip(1.0 - d / margin, 0.0, 1.0)
                return (w * w * (3.0 - 2.0 * w)).astype(np.float32)

            feather_margin = margin
            for suffix, mask in eyes.items():
                eye_falloff[suffix] = feather(mask)
            for suffix, mask in brows.items():
                brow_falloff[suffix] = feather(mask)

        # 2c. Every weight below is a mask, and a mask that jumps between two neighbouring
        # vertices creases the surface even when the displacement it multiplies is
        # perfectly smooth. Radial distance and distance-to-template are both measured
        # per vertex without reference to the mesh, so neither is smooth on the surface by
        # construction -- they have to be relaxed over the topology afterwards. Smoothing
        # a scalar weight is not the Laplacian pass this rewrite removed: that one
        # averaged the displacement itself, which shrank its amplitude and had to be
        # undone with a boost factor. Averaging a 0..1 mask cannot shrink anything.
        M = len(head_indices)
        loc = np.full(N, -1, dtype=np.int64)
        loc[head_indices] = np.arange(M)
        _all_e = np.vstack([faces[:, [0, 1]], faces[:, [1, 2]], faces[:, [2, 0]]])
        _inside = loc[_all_e] >= 0
        head_edges = loc[_all_e[_inside.all(axis=1)]]
        border_edges = _all_e[_inside[:, 0] ^ _inside[:, 1]]

        # The relaxation runs on the WELDED graph -- one node per position, not per index.
        #
        # Every weight handed to `smooth_weights` is a function of position alone: radial
        # distance, distance to the fitted surface, a KD-tree feather. Coincident vertices
        # therefore start out holding identical values. Relaxing over the raw index graph
        # is what pulls them apart: a UV seam splits one point into copies that are NOT
        # joined by an edge -- that is what a seam is -- so each copy averages only the
        # triangles on its own side and after six passes they disagree. Every delta is
        # then multiplied by a weight that differs across the seam, the two sides of the
        # surface move by different amounts, and the mesh opens along the seam.
        #
        # That is not a rounding-level effect on this pipeline's own output. On a
        # 4K-textured character 76% of all vertices are seam copies, and the face split
        # along a network of cracks up to 1.6 median edges wide -- while every edge-based
        # check stayed green, because an edge-based check cannot see two vertices that
        # have no edge between them. Diffusing per position cannot give one point two
        # answers, so the seams stay shut by construction.
        weld = weld_groups(target_head_verts)
        n_weld = int(weld.max()) + 1
        weld_edges = weld[head_edges]
        weld_edges = weld_edges[weld_edges[:, 0] != weld_edges[:, 1]]
        weld_size = np.bincount(weld, minlength=n_weld).astype(np.float64)
        degree = (np.bincount(weld_edges[:, 0], minlength=n_weld)
                  + np.bincount(weld_edges[:, 1], minlength=n_weld)).astype(np.float64)

        def smooth_weights(w: np.ndarray, passes: int = 6) -> np.ndarray:
            w = (np.bincount(weld, weights=np.asarray(w, dtype=np.float64), minlength=n_weld)
                 / weld_size)
            for _ in range(passes):
                neighbour_sum = (
                    np.bincount(weld_edges[:, 0], weights=w[weld_edges[:, 1]], minlength=n_weld)
                    + np.bincount(weld_edges[:, 1], weights=w[weld_edges[:, 0]], minlength=n_weld))
                w = np.where(degree > 0, 0.5 * w + 0.5 * neighbour_sum / np.maximum(degree, 1.0), w)
            return w[weld].astype(np.float32)

        # Where `eyelid_patch` owns the geometry, the transfer has to hand over smoothly
        # instead of stopping dead. The caller zeroes every transferred delta on
        # `protected`, so a weight still at 1.0 on the edge of that region leaves skin
        # moving at full amplitude flush against skin pinned at zero -- a closed C0 step
        # around the eye, measured at 1.000 of the shape's peak. Fading into the boundary
        # makes the two sources meet at the same value.
        #
        # The width of that fade is set in *edges*, not as a fraction of the distance
        # between the eyes. What has to be true is that the handover is spread over enough
        # vertices to read as a slope rather than a step, and how many vertices a given
        # distance buys depends entirely on how finely the character is tessellated.
        if (eye_falloff and protected is not None
                and len(protected) == N and protected.any()):
            edge_len = np.linalg.norm(
                target_head_verts[head_edges[:, 0]] - target_head_verts[head_edges[:, 1]], axis=1)
            hole_margin = max(6.0 * float(np.median(edge_len)), feather_margin * 0.6, 1e-9)
            d_prot, _ = cKDTree(vertices[protected]).query(target_head_verts, k=1)
            h = np.clip(d_prot / hole_margin, 0.0, 1.0)
            handover = (h * h * (3.0 - 2.0 * h)).astype(np.float32)
            eye_falloff = {k: v * handover for k, v in eye_falloff.items()}

        eye_falloff = {k: smooth_weights(v) for k, v in eye_falloff.items()}
        brow_falloff = {k: smooth_weights(v) for k, v in brow_falloff.items()}

        # 3. Correspondence: closest point on the fitted template surface, kept as a
        # triangle plus barycentric weights. Interpolating a per-vertex quantity this way
        # is continuous across the whole surface and linear inside every triangle, so the
        # transferred field inherits the template's own smoothness. The KNN blend this
        # replaces was discontinuous wherever the set of four nearest template vertices
        # changed, and the Laplacian pass that used to hide that also shrank the
        # displacement -- which is what `amplitude_boost` was compensating for.
        fitted_mesh = trimesh.Trimesh(vertices=aligned_src_verts, faces=src_faces, process=False)
        closest, proj_dist, tri_id = trimesh.proximity.closest_point(fitted_mesh, target_head_verts)
        bary = trimesh.triangles.points_to_barycentric(fitted_mesh.triangles[tri_id], closest)
        corner_idx = src_faces[tri_id]                      # (M, 3) template vertex indices
        corner_transforms = vertex_transforms[corner_idx]   # (M, 3, 3, 3)

        # 4. Compute smooth spatial falloff weights (Gaussian feathering at neck/perimeter)
        dists_to_center = np.linalg.norm(target_head_verts - head_center, axis=1)
        r_inner = head_radius * 0.50
        r_outer = head_radius * 0.95

        falloff = np.clip((r_outer - dists_to_center) / max(r_outer - r_inner, 1e-6), 0.0, 1.0)
        falloff = falloff * falloff * (3.0 - 2.0 * falloff)  # Cubic smoothstep (M,)

        # Geometry that the fitted template does not actually cover -- the back of the
        # skull, a neck, a beak the fit could not reach -- lands on the template's nearest
        # boundary triangle and would otherwise pick up that triangle's displacement at
        # full strength. Fade with distance from the fitted surface instead.
        band = max(head_radius * 0.25, 1e-6)
        near = np.clip(1.0 - proj_dist / band, 0.0, 1.0)
        falloff = falloff * (near * near * (3.0 - 2.0 * near))


        # Fade to zero at the boundary of the head region itself. The radial term above
        # vanishes at 0.95 of the head radius, but `detect_head_region` is skeleton-guided
        # and its mask is not that ball -- vertices sit inside the radius yet outside the
        # mask, and vice versa. Every delta is written into the full-mesh array as zero
        # outside the mask, so wherever the two boundaries disagree the field drops from
        # whatever the radial term still allowed straight to nothing across one edge. The
        # field has to fall off at the edge of the region it is actually defined on.
        outside = ~head_mask
        if outside.any():
            touches_outside = np.zeros(M, dtype=bool)
            if len(border_edges):
                inner = np.where(loc[border_edges[:, 0]] >= 0,
                                 border_edges[:, 0], border_edges[:, 1])
                touches_outside[loc[inner]] = True
            if touches_outside.any():
                edge_len = np.linalg.norm(
                    target_head_verts[head_edges[:, 0]] - target_head_verts[head_edges[:, 1]], axis=1)
                rim_band = max(3.0 * float(np.median(edge_len)), head_radius * 0.05)
                d_rim, _ = cKDTree(target_head_verts[touches_outside]).query(target_head_verts, k=1)
                rim = np.clip(d_rim / rim_band, 0.0, 1.0)
                falloff = falloff * (rim * rim * (3.0 - 2.0 * rim))

        falloff = smooth_weights(falloff)

        # 6. Transfer all 52 ARKit blendshapes
        morph_targets: Dict[str, np.ndarray] = {}
        
        # Eye-family blendshapes need to know where the eyes actually are. Without either
        # a detected eye region or a detected pair of eye landmarks, the template lands by
        # a bounding-sphere guess, and an eyeBlink placed by guesswork deforms whatever
        # happens to sit there. Skip them instead.
        eyes_located = eye_regions is not None or (
            target_landmarks is not None
            and "left_eye" in target_landmarks and "right_eye" in target_landmarks
        )
        if not eyes_located:
            print("[FacialBlendshapes] Eyes not located; skipping eye blendshapes.")

        for bs_name, src_delta in self.source_deltas.items():
            if bs_name.startswith("eye") and not eyes_located:
                continue

            # Carry each corner's template-space displacement through that corner's own
            # linear transform from the fit, then blend the three by the barycentric
            # weights. Using the per-vertex transform rather than one global rotation is
            # what keeps a brow displacement pointing along the target's brow ridge on a
            # head whose proportions differ from the template's.
            corner_deltas = np.einsum('mkij,mkj->mki', corner_transforms, src_delta[corner_idx])
            tgt_head_delta = np.einsum('mk,mki->mi', bary, corner_deltas)  # (M, 3)
            if amplitude_boost != 1.0:
                tgt_head_delta = tgt_head_delta * amplitude_boost

            # Apply feathering falloff so boundary blends to 0 displacement
            tgt_head_delta *= falloff[:, None]

            # Constrain side-specific blendshapes to the region they belong to, if found.
            # `browInnerUp` carries no side suffix -- it is one bilateral shape spanning
            # both brows -- so it matches nothing here and stays unconstrained, which is
            # correct: clamping it to one side would pull only half of it.
            region = (eye_falloff if bs_name.startswith("eye")
                      else brow_falloff if bs_name.startswith("brow") else None)
            if region:
                for suffix, w in region.items():
                    if bs_name.endswith(suffix):
                        tgt_head_delta *= w[:, None]
                        break

            # Place into full mesh delta array of size (N, 3)
            full_delta = np.zeros((N, 3), dtype=np.float32)
            full_delta[head_indices] = tgt_head_delta.astype(np.float32)

            # 7. Adaptive Full-Closure Eyelid Scaling for Anime / Chibi / Big-Eyed Characters
            # In human templates, eyelids travel ~1.5cm down, which on huge cartoon/chibi eyes (10-15cm tall)
            # only squints 10% instead of fully shutting the eyelid. We detect the actual eye height
            # and scale vertical travel so the upper eyelid fully reaches the lower eyelid when weight=1.0.
            #
            # Only when there are no lids. It stretches along the *world* Y axis, so it is
            # wrong the moment the head is tilted, and where `eyelid_patch` built real lid
            # geometry that geometry already closes the eye properly -- there this would
            # only stretch the surrounding skin along an arbitrary axis.
            if bs_name.startswith("eye") and protected is None:
                disp_mag = np.linalg.norm(full_delta, axis=1)
                active_idx = np.where(disp_mag > 1e-4)[0]
                if len(active_idx) > 0:
                    # Clean up spurious distant movements (eliminate leakage onto turtle shell, neck, or body)
                    eye_center_est = vertices[active_idx].mean(axis=0)
                    eye_dist = np.linalg.norm(vertices[active_idx] - eye_center_est, axis=1)
                    max_allowed_r = min(head_radius * 0.75, 0.12)
                    spurious = active_idx[eye_dist > max_allowed_r]
                    if len(spurious) > 0:
                        full_delta[spurious] = 0.0

                    # Re-calculate on valid eye vertices
                    valid_idx = np.where(np.linalg.norm(full_delta, axis=1) > 1e-4)[0]
                    if len(valid_idx) > 0 and bs_name in ("eyeBlinkLeft", "eyeBlinkRight", "eyeSquintLeft", "eyeSquintRight"):
                        eye_pts = vertices[valid_idx]
                        y_min, y_max = float(eye_pts[:, 1].min()), float(eye_pts[:, 1].max())
                        eye_h = max(y_max - y_min, 1e-4)
                        cur_max = float(np.linalg.norm(full_delta[valid_idx], axis=1).max())

                        target_close_h = eye_h * (0.85 if "Blink" in bs_name else 0.40)
                        if cur_max < target_close_h and cur_max > 1e-5:
                            scale_factor = target_close_h / cur_max
                            full_delta[valid_idx, 1] *= scale_factor
                            full_delta[valid_idx, 2] += np.abs(full_delta[valid_idx, 1]) * 0.12

            if np.abs(full_delta).max() > 1e-5:
                morph_targets[bs_name] = full_delta

        # The eye family is no longer built here. Every shape that used to live in this
        # spot displaced the painted eye's own vertices, and a displacement field applied to
        # a painted circle produces an ellipse -- the pupil tore out of shape on every one
        # of them. `pipeline.eyelid_patch` now supplies eyeBlink / eyeSquint / eyeWide and
        # the whole eyeLook family from geometry that either moves rigidly (the iris cap) or
        # is not part of the eye at all (the lids, the surrounding skin). The caller masks
        # this function's output over that geometry before merging the two.

        elapsed = time.time() - t0
        print(f"[FacialBlendshapes] Successfully transferred {len(morph_targets)} ARKit blendshapes in {elapsed:.2f}s (head vertices: {len(head_indices)}/{N})")
        return morph_targets
